### PR TITLE
changed install method

### PR DESCRIPTION
**Pull request by MStruller**
change install method to upgrade in the manifest
and change install.php to upgrade also the modules/plugins

### CODE REVIEW

**Comment by akempkens** [comment]
Are you sure this is a good way to do?

This will be the first release for 2.5 and actually I do not expect anybody to have a previous version installed. They should actually not upgrade but install this first release on a fresh Joomla 2.5 installation.

I fear we mess the later automatic upgrade process within Joomla core extension manager - not sure about it.

**Comment by MStruller** [comment]
<pre>This will be the first release for 2.5 and actually I do not expect anybody to have a previous version installed. They should actually not upgrade but install this first release on a fresh Joomla 2.5 installation.</pre>

Ok, i have not showw from this site , only i have look at the current situation where i install the developer version not only one

**Comment by akempkens** [comment]
What we can consider is to have a simple way now using the upgrade method and have it on our "todo for release" list before the official release goes out.

**Comment by MStruller** [comment]
ok, thats great
where is the todo list?

**Comment by akempkens** [comment]
link related the todo list sent to your email.

**Comment by akempkens** [comment]
According to time we will stay with the upgrade. Some people might have installed the existing version already.

**Pull request closed without merging**
